version: "3"

services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password
            - SERVICE_PORTS=5672
            - TCP_PORTS=5672
        networks:
            - benchopnet
        ports:
            - 5671
            - 5672
            - 15672
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3
            placement:
                constraints: [node.role==worker]

    flaskapp:
        image: flaskapp:v1.0
        depends_on:
            - rabbitmq
            - celeryworker
        networks:
            - benchopnet
        ports:
            - 5000:4567
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3
            placement:
                constraints: [node.role==manager]

    celeryworker:
        image: flaskapp:v1.0
        command: celery -A tasks worker -l info
        depends_on:
            - rabbitmq
        networks:
            - benchopnet
        deploy:
            replicas: 8
            restart_policy:
                condition: on-failure
                max_attempts: 3

networks:
    benchopnet:
        driver: overlay 
